version: '3'
services:
  app:
    container_name: sagemaker
    build: .
    volumes:
      - type: bind
        source: .
        target: /root/sagemaker-logistic-regression
    working_dir: /root/sagemaker-logistic-regression
    entrypoint: bash
    stdin_open: true
    tty: true
    ports:
      - 5000:5000
